"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Poppins } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastProvider } from "@/components/provider/toaster.provider";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      afterSignOutUrl={"/"}
      appearance={{
        variables: {
          colorTextSecondary: "#454545",
          colorTextOnPrimaryBackground: "#ffffff",
          colorPrimary: "#3657FF",
          colorBackground: "#D9E2FF",
          colorInputBackground: "#FFFFFF",
          colorText: "#121212",
          colorWarning: "#F5B40B",
          colorDanger: "#DC2626",
          colorNeutral: "#121212",
          colorInputText: "#121212",
        },
      }}
    >
      <html lang="fr">
        <body
          className={`${manrope.className} ${poppins.className} bg-blue-ribbon-50`}
        >
          <ToastProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
