"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Poppins } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastProvider } from "@/components/provider/toaster.provider";
import { useEffect } from "react";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    console.log("RootLayout has mounted");
  }, []);

  return (
    <ClerkProvider>
      <html lang="fr">
        <body
          className={`${manrope.className} ${poppins.className} bg-blue-ribbon-50`}
        >
          <ToastProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
